TAGS = {
	'Parking': (['JustPark', 'Westquay Car Park', 'Southgate Carpark'], 'Transport'),
	'Groceries': (['Tesco', 'Co-op', 'Sainsburys', 'Asda', 'Lidl', 'Waitrose', 'Aldi'], 'Food'),
	'Resturaunt': (['JustPark', 'Adventure Cafe', 'Gourmet Burger Kitchen', 'Southampton Catering', 'Handmade Burger Co', 'Franco Manca', 'Pret A Manger', 'Gandhi Of Portswood', 'Dough Pizza', 'Wahaca', 'Nandos', 'Giraffe', 'Cosmo', 'Las Iguanas', 'Aldi', 'The Boston Tea Party', 'Trago Lounge'], 'Food'),
	'Saving': ([], 'Income'),
	'Interest': (['Interest'], 'Income'),
	'Wages': (['Bath University', 'Student Loans Company', 'Amazon', 'Buckle Consulting', 'Bath University Payroll', 'Netcraft'], 'Income'),
	'Loan': (['Student Loans Company', 'Amazon'], 'Income'),
	'Rent': (['Southampton University', 'Student No Fee'], 'Household'),
	'Takeaway': (['Dominos', 'Uber Eats', 'PizzaGoGo', 'Just Eat', 'Deliveroo'], 'Food'),
	'Bus': (['First Bus', 'Go South Coast', 'Carphone Warehouse'], 'Transport'),
	'Train': (['Great Western Railway'], 'Transport'),
	'Fuel': (['Sainsburys Petrol', 'Shell'], 'Transport'),
	'Taxi': (['Uber', 'Cab My Ride'], 'Transport'),
	'Café': (['Costa Coffee', 'Coffee #1', 'Pumpkin Cafe', 'Starbucks'], 'Food'),
	'Cashback': (['Retailer Offers Cashback'], 'Income'),
	'Pub': (['Bath Brew House', 'The Crown Inn', 'Brewhouse And Kitchen', 'Thatchers Cider', 'Pig & Fiddle', 'Wetherspoons', 'The Mitre'], 'Entertainment'),
	'Club': (['Jesters', 'Oceana', 'Switch Southmapton', 'Sobar Southampton', 'Carphone Warehouse'], 'Entertainment'),
	'Bar': (['Grand Cafe', 'Juno', 'Carphone Warehouse'], 'Entertainment'),
	'Gaming': (['Steam', 'Carphone Warehouse'], 'Entertainment'),
	'Purchase': (['Kickstarter', 'The Pi Hut', 'Currys PC World', 'Carphone Warehouse', 'Amazon', 'Ks Market'], 'None'),
	'Person': (['Vishnuga Uthayamohan', 'Thujhan Yogeswaran', 'Dylan Marodeen', 'Josh Sanchez', 'Bethany Shaw', 'Sophie James', 'Sian Williams', 'Naomi Buddle', 'Savarna Chaddha', 'Oscar Case', 'Katie', 'Lucy Weddell', 'Emily Langrish', 'Carphone Warehouse', 'Cliff Waters', 'Lesley Waters'], 'Personal'),
	'Event': (['Fixr Tickets', 'Southampton SU Box Office', 'Fatsoma', 'Carphone Warehouse'], 'Entertainment'),
	'Appstore': (['Google Play'], 'Entertainment'),
	'Fast Food': (['Mcdonalds', 'Chick O Land', 'Millies Cookies', 'Taco Bell', 'Subway', 'Burger King'], 'Food'),
	'Clothing': (['Marks & Spencer', 'Primark'], 'None'),
	'Insurance': (['Cover 4 Insurance'], 'Household'),
	'Dessert': (['Sprinkles Gelato', 'Scoops Gelato', 'Isaacs Gelato'], 'Food'),
	'Furniture': (['Ikea'], 'None'),
	'Government': (['Disclosure and Barring Service', 'DVLA'], 'None'),
	'Plane': (['Easyjet'], 'Transport'),
	'Sport': (['Recbad'], 'None'),
	'Development': (['Google Domains'], 'None'),
	'Gym': (['Genesis Lifestyle Centre'], 'None'),
	'Test': ([], 'None'),
}
