TAGS = {
	'Parking': (['JustPark', 'Westquay Car Park', 'Southgate Carpark', 'Brighton Parking'], 'Transport'),
	'Groceries': (['Tesco', 'Co-op', 'Sainsburys', 'Asda', 'Lidl', 'Waitrose', 'Iceland', 'Spar'], 'Food'),
	'Resturaunt': (['Gourmet Burger Kitchen', 'Southampton Catering', 'Handmade Burger Co', 'Franco Manca', 'Pret A Manger', 'Gandhi Of Portswood', 'Dough Pizza', 'Wahaca', 'Nandos', 'Giraffe', 'Cosmo', 'Las Iguanas', 'Aldi', 'The Boston Tea Party', 'Trago Lounge', 'The Lime Tree (Bath Uni)', 'La Baronia', 'Wagamama', 'The Botanist', 'Carluccios', "Ed\\'s Easy Diner", 'Cosy Club', 'Poppins', 'Forte Kitchen', 'Gandhi'], 'Food'),
	'Saving': ([], 'Income'),
	'Interest': (['Interest'], 'Income'),
	'Wages': (['Bath University', 'Buckle Consulting', 'Bath University Payroll', 'Netcraft', 'Southampton University Payroll'], 'Income'),
	'Loan': (['Student Loans Company'], 'Income'),
	'Rent': (['Southampton University', 'Student No Fee'], 'Household'),
	'Takeaway': (['Dominos', 'Uber Eats', 'PizzaGoGo', 'Just Eat', 'Deliveroo', 'Fish N Fritz'], 'Food'),
	'Bus': (['First Bus', 'Go South Coast', 'Unilink'], 'Transport'),
	'Train': (['Great Western Railway', 'South Western Railway', 'Transport for London', 'National Railcard', 'National Rail'], 'Transport'),
	'Fuel': (['Sainsburys Petrol', 'Shell'], 'Transport'),
	'Taxi': (['Uber', 'Cab My Ride'], 'Transport'),
	'Café': (['Costa Coffee', 'Coffee #1', 'Pumpkin Cafe', 'Starbucks', 'Society Cafe', 'The Bath Coffee Company', 'Small Batch Coffee Company', 'Caffe Nero'], 'Food'),
	'Cashback': (['Retailer Offers Cashback'], 'Income'),
	'Pub': (['Bath Brew House', 'The Crown Inn', 'Brewhouse And Kitchen', 'Thatchers Cider', 'Pig & Fiddle', 'Wetherspoons', 'The Mitre', 'The Star Inn', 'Belushis Bath', 'The Locksbrook Inn', 'Lamb & Lion Pub'], 'Entertainment'),
	'Club': (['Jesters', 'Oceana', 'Switch Southmapton', 'Sobar Southampton', 'Lizard Lounge', 'Suburbia', 'Rebel', 'Moles', 'The Nest', 'Zero Zero Nightclub', 'Weir Lounge'], 'Entertainment'),
	'Bar': (['Grand Cafe', 'Juno', 'Wild Lime', 'Slug and Lettuce', 'Adventure Cafe'], 'Entertainment'),
	'Gaming': (['Steam', 'Blizzard Entertainment'], 'Entertainment'),
	'Purchase': (['Kickstarter', 'The Pi Hut', 'Currys PC World', 'Amazon', 'Ks Market', 'Indiegogo'], 'Personal'),
	'Person': (['Vishnuga Uthayamohan', 'Thujhan Yogeswaran', 'Dylan Marodeen', 'Josh Sanchez', 'Bethany Shaw', 'Sophie James', 'Sian Williams', 'Naomi Buddle', 'Savarna Chaddha', 'Oscar Case', 'Katie', 'Lucy Weddell', 'Emily Langrish', 'Carphone Warehouse', 'Cliff Waters', 'Lesley Waters', 'Catriona McKay', 'Kieran Miller', 'Cameron Wright', 'Suzie Fieldwick', 'AJ Stoffer', 'Nicholas Dwyer', 'Maddie Rushworth', 'Ruth Dwyer', 'Luke Taylor'], 'Personal'),
	'Event': (['Fixr Tickets', 'Southampton SU Box Office', 'Fatsoma'], 'Entertainment'),
	'Appstore': (['Google Play'], 'Entertainment'),
	'Fast Food': (['Mcdonalds', 'Chick O Land', 'Millies Cookies', 'Taco Bell', 'Subway', 'Burger King', 'KFC', 'Charcoal Grill', "Mr D\\'s", 'Ralph Allen School', 'Southampton SU'], 'Food'),
	'Clothing': (['Marks & Spencer', 'Primark', 'H&M', 'River Island', 'Sports Direct', 'Debenhams', 'Blacks'], 'Personal'),
	'Insurance': (['Cover 4 Insurance', 'Virgin Travel Insurance'], 'Household'),
	'Dessert': (['Sprinkles Gelato', 'Scoops Gelato', 'Isaacs Gelato'], 'Food'),
	'Furniture': (['Ikea'], 'Household'),
	'Government': (['Disclosure and Barring Service', 'DVLA'], 'Household'),
	'Plane': (['Easyjet'], 'Transport'),
	'Sport': (['Recbad'], 'Health'),
	'Development': (['Google Domains'], 'Personal'),
	'Gym': (['Genesis Lifestyle Centre'], 'Health'),
	'Test': ([], 'None'),
	'Pharmacy': (['Jhoots Pharmacy', 'Superdrug', 'Boots'], 'Health'),
	'Bills': (['Southern Water', 'Bills'], 'Household'),
	'Phone': (['ID Mobile (Via Clifford Waters)'], 'Household'),
	'Vending Machine': (['Selecta Uk (Vending Machine)'], 'Food'),
}
