TARGETS = {
	'123 Student': [],
	'Regular Saver': [],
	'ESaver': [],
	'Tandem 1YR Fixed': ['1y fixed saver'],
	'Tandem 2YR Fixed': ['2y fixed saver'],
	'Tandem 3YR Fixed': ['tandem 3y'],
	'Monzo': ['monzo'],
	'Crowdcube': ['crowdcube'],
	'Freetrade': ['freetrade'],
	'Wealthsimple': ['wealthsimple'],
	'Nutmeg': ['nutmeg'],
	'Vanguard': ['vanguard'],
	'Amazon': ['amznmktplace'],
	'JustPark': ['justpark'],
	'Tesco': ['tesco'],
	'Student Loans Company': ['slc disbursements'],
	'Southampton University': ['www.soton.ac.uk'],
	'Bath University': ['univ bath students uni'],
	'Dominos': ['dominos'],
	'Co-op': ['co-op group'],
	'Bath Brew House': ['bath brew house'],
	'Adventure Cafe': ['adventure cafe'],
	'Buckle Consulting': ['buckle consu ltd'],
	'Gourmet Burger Kitchen': ['gourmet burger kit'],
	'First Bus': ['first bus', 'first west of england', 'www.firstgroup.com'],
	'Steam': ['steamgames.com', 'valve gmbh'],
	'Sainsburys': ['sainsburys s/mkts', 'sainsburys', 'js online grocery'],
	'Southgate Carpark': ['southgate shopping'],
	'Mcdonalds': ['mcdonalds'],
	'Costa Coffee': ['costa coffee', 'costa'],
	'Deliveroo': ['deliveroo.co.uk'],
	'Thujhan Yogeswaran': ['mr thujhan yogeswaran'],
	'Vishnuga Uthayamohan': ['vishnuga uthayamohan'],
	'Uber': ['uber *trip', 'uber trip', 'ubr* pending.uber.com', 'uber bv'],
	'Oceana': ['southampton - oceana', 'www.delticgroup.co.uk'],
	'Sainsburys Petrol': ['sainsburys petrol'],
	'Chick O Land': ['chick o land'],
	'Jesters': ['jester night', 'clowns and jesters'],
	'Dylan Marodeen': ['dylan marodeen', 'marodeen d j', 'dylan'],
	'Fatsoma': ['www.fatsoma.com'],
	'Southampton Catering': ['catering office'],
	'Handmade Burger Co': ['handmade burger co'],
	'The Crown Inn': ['the crown inn'],
	'Asda': ['asda superstore'],
	'Millies Cookies': ['millies cookies'],
	'Nandos': ['nandos'],
	'Oscar Case': ['mr oscar david case'],
	'Josh Sanchez': ['sanchez carabal jf'],
	'Southampton SU': ['uni of southampton su', 'susu.org'],
	'Uber Eats': ['uber eats help.uber.com', 'uber eats', 'uber *eats'],
	'Bethany Shaw': ['miss bethany shaw', 'bethany'],
	'Franco Manca': ['franco manca'],
	'Sophie James': ['james sog', 'sophie'],
	'Google Play': ['google *google play'],
	'Disclosure and Barring Service': ['disclosure and barring'],
	'Pret A Manger': ['pret a manger'],
	'Sian Williams': ['williams c s', 'miss chloe sian williams', 'sian'],
	'DVLA': ['dvla'],
	'Marks & Spencer': ['marks&spencer', 'm&s simply food'],
	'Starbucks': ['starbucks'],
	'Wetherspoons': ['j d wetherspoon', 'three fishes', 'king of wessex'],
	'The Mitre': ['mitre'],
	'Giraffe': ['giraffe concepts'],
	'Taco Bell': ['taco bell'],
	'Cheque': ['cheque paid in'],
	'Grand Cafe': ['grand cafe'],
	'Cab My Ride': ['cab my ride'],
	'Go South Coast': ['go south coast'],
	'Sprinkles Gelato': ['sprinkles gelato'],
	'Brewhouse And Kitchen': ['brewhouse and kitc'],
	'Interest': ['interest paid after tax'],
	'Subway': ['subway'],
	'Gandhi Of Portswood': ['gandhi of portswood'],
	'Great Western Railway': ['gwr websales', 'gwr delay repay', 'www.gwr.com'],
	'Scoops Gelato': ['scoops gelato'],
	'Ikea': ['ikea limited', 'ikea ltd'],
	'Katie': ['katie', 'thompson kam'],
	'Cosmo': ['cosmo'],
	'Primark': ['primark'],
	'Isaacs Gelato': ['isaacs gelato ltd'],
	'Lucy Weddell': ['lucy alison weddell'],
	'Switch Southmapton': ['switch southmapton', 'switch'],
	'Shell': ['shell'],
	'Coffee #1': ['coffee1', 'coffee no 1', 'coffeeñ1'],
	'Cash Withdrawal': ['cash withdrawal'],
	'Retailer Offers Cashback': ['retailer offers cashback', 'my offers cash earnings'],
	'Pumpkin Cafe': ['pumpkin cafe'],
	'Ks Market': ['ks market'],
	'Google Domains': ['google *domains'],
	'Rockbottom Toys': ['rockbottom toys'],
	'Student No Fee': ['student no fee', 'studnofee'],
	'Dough Pizza': ['dough pizza ltd'],
	'Emily Langrish': ['*emilylangr7', 'langrish ej'],
	'Easyjet': ['easyjet'],
	'Lidl': ['lidl gb', 'lidl uk'],
	'Juno': ['juno'],
	'Netcraft': ['netcraft'],
	'Kickstarter': ['kickstarter.com'],
	'Aldi': ['aldi'],
	'PizzaGoGo': ['www.pizzagogo.co.uk'],
	'Just Eat': ['just eat'],
	'Wahaca': ['wahaca'],
	'Thatchers Cider': ['thatchers cider', 'thatcherscidertour'],
	'Ed\'s Easy Diner': ["ed's easy diner"],
	'Carphone Warehouse': ['carphone warehouse'],
	'Westquay Car Park': ['westquay car park'],
	'WHSmith': ['wh smith'],
	'Southampton University Payroll': ['university of sout,payroll', 'university of sout payroll', 'university of sout payroll'],
	'Pig & Fiddle': ['pig & fiddle'],
	'Sobar Southampton': ['sobar southampton'],
	'Recbad': ['toby recbad', 'lawrence recbad'],
	'Fixr Tickets': ['fixr event tickets'],
	'Bath University Payroll': ['uni of bath payrol'],
	'The Pi Hut': ['thepihut'],
	'Southampton SU Box Office': ['www.boxoffice.susu.org'],
	'Naomi Buddle': ['n buddle', 'naomi buddle'],
	'Las Iguanas': ['las iguanas'],
	'Waitrose': ['waitrose'],
	'Savarna Chaddha': ['savarna chaddha'],
	'Burger King': ['welcome break bk', 'burger king'],
	'Currys PC World': ['currys stores'],
	'Trago Lounge': ['trago lounge'],
	'Paypal': ['paypal code', '*paypal credit', 'paypal'],
	'ECSS': ['*ecss'],
	'The Boston Tea Party': ['the boston tea party'],
	'Cover 4 Insurance': ['www.cover4insurance.com'],
	'Cliff Waters': ['clifford william waters'],
	'Lesley Waters': ['lesley susan waters'],
	'Genesis Lifestyle Centre': ['genesis lifestyle centre'],
	'Odeon': ['odeon'],
	'National Rail': ['selfserve ticket'],
	'Oak North 6mth': ['oak north reference 6 month savings'],
	'Marcus': ['marcus savings'],
	'KFC': ['kfc'],
	'Wild Lime': ['wild lime'],
	'Poppins': ['poppins'],
	'Bills': ['account 090129 40359139'],
	'Indiegogo': ['indiegogo'],
	'Southern Water': ['southern water service'],
	'Post Office': ['postoffice', 'post office'],
	'LTEST': ['abcd', 'abcde'],
	'South Western Railway': ['south western railway', 'swrailwayselfserve'],
	'Iceland': ['iceland'],
	'Cameron Wright': ['mr cameron james wright'],
	'Charlie\'s  Bargain Booze': ['charlie s bargain booz'],
	'Suzie Fieldwick': ['fieldwick s'],
	'AJ Stoffer': ['a stoffer', 'aj'],
	'Transport for London': ['tfl travel', 'tfl.gov.uk/cp'],
	'AirBnB': ['airbnb'],
	'Hostel World': ['hostel world'],
	'SUCB': ['sucb tour'],
	'H&M': ['h & m'],
	'Maddie Rushworth': ['miss madeleine constance maud rushworth'],
	'Zero Zero Nightclub': ['zero zero nightclub'],
	'Lamb & Lion Pub': ['lamb & lion'],
	'Belushis Bath': ['belushis bath'],
	'Debenhams': ['debenhams'],
	'Ruth Dwyer': ['ruth dwyer'],
	'Luke Taylor': ['luke anthony taylor'],
	'ID Mobile (Via Clifford Waters)': ['account 090127 08444024 mandate no 12', 'account 090127 08444024, mandate no 12'],
	'Ralph Allen School': ['www.ralphallen.bathnes', 'ralph allen school'],
	'Ryman': ['ryman'],
	'Waterstones': ['waterstones'],
	'Foreign Purchase Fee': ['non-sterling purchase fee', 'foreign currency purchase fee'],
	'Poundland': ['poundland ltd'],
	'The Lime Tree (Bath Uni)': ['the lime tree'],
	'Cosy Club': ['cosy club'],
	'Catriona McKay': ['c mckay', 'mckay catriona'],
	'Slug and Lettuce': ['slug and lettuce'],
	'Tiger': ['tiger'],
	'Society Cafe': ['*society cafe limited'],
	'River Island': ['river island'],
	'Gandhi': ['gandhi'],
	'Suburbia': ['suburbia'],
	'Charcoal Grill': ['charcoal grill'],
	'Wilko': ['wilko retail limited', 'wilko'],
	'Lizard Lounge': ['lizard lounge'],
	'Nicholas Dwyer': ['dwyer+lee-dwy'],
	'Hollywood Bowl': ['hollywood bowl'],
	'Etsy': ['etsy.com'],
	'Unilink': ['unilink'],
	'Rebel': ['rebel'],
	'Carluccios': ['carluccio s'],
	'Superdrug': ['superdrug stores'],
	'Virgin Travel Insurance': ['virgin travel insur'],
	'The Locksbrook Inn': ['the locksbrook inn'],
	'Mr D\'s': ["mr d's"],
	'The Star Inn': ['the star inn'],
	'Sports Direct': ['sportsdirect'],
	'Queens Square Dental': ['queens square dental'],
	'National Railcard': ['national railcard'],
	'Kieran Miller': ['miller kieran'],
	'Small Batch Coffee Company': ['small batch coffee comp'],
	'Pyramid Posters': ['pyramid posters limited'],
	'Boots': ['boots'],
	'Lego': ['lego'],
	'The Bath Coffee Company': ['the bath coffee compan'],
	'Moles': ['moles'],
	'Spar': ['spar'],
	'Caffe Nero': ['caffe nero'],
	'The Botanist': ['the botanist'],
	'Vinegar Hill': ['vinegar hill'],
	'Bath On Ice': ['bath on ice'],
	'Blizzard Entertainment': ['blizzard entertainment'],
	'1&1 Internet': ['1&1 internet limited'],
	'Lifx': ['lifx'],
	'Wagamama': ['wagamama'],
	'Hobbycraft': ['hobbycraft'],
	'Modmypi': ['modmypi'],
	'The Nest': ['the nest'],
	'Portswood Hardware': ['portswood hardware'],
	'Coinbase': ['coinbase'],
	'Forte Kitchen': ['forte kitchen'],
	'Selecta Uk (Vending Machine)': ['selecta uk', 'selecta u.k.'],
	'Highermoor Farm': ['www.highermoorfarm.co.uk'],
	'Matthew Paul Interiors': ['matthew paul interiors'],
	'Fish N Fritz': ['fish n fritz'],
	'Blacks': ['blacks'],
	'Warminster Services': ['warminster forecourt'],
	'Leigh Delamere Services': ['leigh delamere east', 'leigh delamere s/w'],
	'Weir Lounge': ['weir lounge'],
	'La Baronia': ['la baronia'],
	'Southampton General Hospital': ['southampton general ho'],
	'Brighton Parking': ['brighton & hove city c'],
	'Winchester Christmas Market': ['*the gourmet grilled'],
	'Jhoots Pharmacy': ['jhoots'],
}
