TARGETS = {
	'123 Student': [],
	'Regular Saver': [],
	'ESaver': [],
	'Tandem 1YR Fixed': ['1y fixed saver'],
	'Tandem 2YR Fixed': ['2y fixed saver'],
	'Tandem 3YR Fixed': ['tandem 3y'],
	'Monzo': ['monzo'],
	'Crowdcube': ['crowdcube'],
	'Freetrade': ['freetrade'],
	'Wealthsimple': ['wealthsimple'],
	'Nutmeg': ['nutmeg'],
	'Vanguard': ['vanguard'],
	'Amazon': ['amzn', 'amazon prime', 'amazon.co.uk'],
	'JustPark': ['justpark'],
	'Tesco': ['tesco'],
	'Student Loans Company': ['slc disbursements'],
	'Southampton University': ['www.soton.ac.uk'],
	'Bath University': [],
	'Dominos': ['dominos'],
	'Co-op': ['co-op group'],
	'Bath Brew House': ['bath brew house'],
	'Adventure Cafe': ['adventure cafe'],
	'Buckle Consulting': ['buckle consu ltd'],
	'Gourmet Burger Kitchen': ['gourmet burger kit'],
	'First Bus': ['first bus', 'first west of england', 'www.firstgroup.com'],
	'Steam': ['steamgames.com'],
	'Sainsburys': ['sainsburys s/mkts', 'sainsburys'],
	'Southgate Carpark': ['southgate shopping'],
	'Mcdonalds': ['mcdonalds'],
	'Costa Coffee': ['costa coffee'],
	'Deliveroo': ['deliveroo.co.uk'],
	'Thujhan Yogeswaran': ['mr thujhan yogeswaran'],
	'Vishnuga Uthayamohan': ['vishnuga uthayamohan'],
	'Uber': ['uber *trip', 'uber trip', 'ubr* pending.uber.com', 'uber bv'],
	'Oceana': ['southampton - oceana'],
	'Sainsburys Petrol': ['sainsburys petrol'],
	'Chick O Land': ['chick o land'],
	'Jesters': ['jester night'],
	'Dylan Marodeen': ['dylan marodeen', 'marodeen d j', 'dylan'],
	'Fatsoma': ['www.fatsoma.com'],
	'Southampton Catering': ['catering office'],
	'Handmade Burger Co': ['handmade burger co'],
	'The Crown Inn': ['the crown inn'],
	'Asda': ['asda superstore'],
	'Millies Cookies': ['millies cookies'],
	'Nandos': ['nandos'],
	'Oscar Case': ['mr oscar david case'],
	'Josh Sanchez': ['sanchez carabal jf'],
	'Southampton SU': ['uni of southampton su'],
	'Uber Eats': ['uber eats help.uber.com', 'uber eats', 'uber *eats'],
	'Bethany Shaw': ['miss bethany shaw'],
	'Franco Manca': ['franco manca'],
	'Sophie James': ['james sog', 'sophie'],
	'Google Play': ['google *google play'],
	'Disclosure and Barring Service': ['disclosure and barring'],
	'Pret A Manger': ['pret a manger'],
	'Sian Williams': ['williams c s', 'miss chloe sian williams', 'sian'],
	'DVLA': ['dvla'],
	'Marks & Spencer': ['marks&spencer'],
	'Starbucks': ['starbucks'],
	'Wetherspoons': ['j d wetherspoon', 'three fishes'],
	'The Mitre': ['mitre'],
	'Giraffe': ['giraffe concepts'],
	'Taco Bell': ['taco bell'],
	'Cheque': ['cheque paid in'],
	'Grand Cafe': ['grand cafe'],
	'Cab My Ride': ['cab my ride'],
	'Go South Coast': ['go south coast'],
	'Sprinkles Gelato': ['sprinkles gelato'],
	'Brewhouse And Kitchen': ['brewhouse and kitc'],
	'Interest': ['interest paid after tax'],
	'Subway': ['subway'],
	'Gandhi Of Portswood': ['gandhi of portswood'],
	'Great Western Railway': ['gwr websales', 'gwr delay repay', 'www.gwr.com'],
	'Scoops Gelato': ['scoops gelato'],
	'Ikea': ['ikea limited'],
	'Katie': ['katie', 'thompson kam'],
	'Cosmo': ['cosmo'],
	'Primark': ['primark'],
	'Isaacs Gelato': ['isaacs gelato ltd'],
	'Lucy Weddell': ['lucy alison weddell'],
	'Switch Southmapton': ['switch southmapton', 'switch'],
	'Shell': ['shell'],
	'Coffee #1': ['coffee1', 'coffee no 1'],
	'Cash Withdrawal': ['cash withdrawal'],
	'Retailer Offers Cashback': ['retailer offers cashback', 'my offers cash earnings'],
	'Pumpkin Cafe': ['pumpkin cafe'],
	'Ks Market': ['ks market'],
	'Google Domains': ['google *domains'],
	'Rockbottom Toys': ['rockbottom toys'],
	'Student No Fee': ['student no fee', 'studnofee'],
	'Dough Pizza': ['dough pizza ltd'],
	'Emily Langrish': ['*emilylangr7', 'langrish ej'],
	'Easyjet': ['easyjet'],
	'Lidl': ['lidl gb', 'lidl uk'],
	'Juno': ['juno'],
	'Netcraft': ['netcraft'],
	'Kickstarter': ['kickstarter.com'],
	'Aldi': ['aldi'],
	'PizzaGoGo': ['www.pizzagogo.co.uk'],
	'Just Eat': ['just eat'],
	'Wahaca': ['wahaca'],
	'Thatchers Cider': ['thatchers cider', 'thatcherscidertour'],
	'Ed\'s Easy Diner': ["ed's easy diner"],
	'Carphone Warehouse': ['carphone warehouse'],
	'Westquay Car Park': ['westquay car park'],
	'WHSmith': ['wh smith'],
	'Southampton University Payroll': ['university of sout,payroll'],
	'Pig & Fiddle': ['pig & fiddle'],
	'Sobar Southampton': ['sobar southampton'],
	'Recbad': ['toby recbad'],
	'Fixr Tickets': ['fixr event tickets'],
	'Bath University Payroll': ['uni of bath payrol'],
	'The Pi Hut': ['thepihut'],
	'Southampton SU Box Office': ['www.boxoffice.susu.org'],
	'Naomi Buddle': ['n buddle', 'naomi buddle'],
	'Las Iguanas': ['las iguanas'],
	'Waitrose': ['waitrose'],
	'Savarna Chaddha': ['savarna chaddha'],
	'Burger King': ['welcome break bk'],
	'Currys PC World': ['currys stores'],
	'Trago Lounge': ['trago lounge'],
	'Paypal': ['paypal code'],
	'ECSS': ['*ecss'],
	'The Boston Tea Party': ['the boston tea party'],
	'Cover 4 Insurance': ['www.cover4insurance.com'],
	'Cliff Waters': ['clifford william waters'],
	'Lesley Waters': ['lesley susan waters'],
	'Genesis Lifestyle Centre': ['genesis lifestyle centre'],
	'Odeon': ['odeon'],
	'National Rail': ['selfserve ticket'],
	'Oak North 6mth': ['oak north reference 6 month savings'],
	'Marcus': ['marcus savings'],
	'KFC': ['kfc'],
	'Wild Lime': ['wild lime'],
	'Poppins': ['poppins'],
	'Bills': ['account 090129 40359139'],
	'Indiegogo': ['indiegogo'],
	'Southern Water': ['southern water service'],
}
