TARGETS = {
	'123 Student': [],
	'Regular Saver': [],
	'ESaver': [],
	'Amazon': ['amzn', 'amazon prime'],
	'JustPark': ['justpark'],
	'Tesco': ['tesco'],
	'Student Loans Company': ['slc disbursements'],
	'Southampton University': ['www.soton.ac.uk'],
	'Bath University': [],
	'Dominos': ['dominos'],
	'<internal>': ['transfer from mr james clifford waters'],
	'Co-op': ['co-op group'],
	'Crowdcube': ['crowdcube'],
	'Bath Brew House': ['bath brew house'],
	'Adventure Cafe': ['adventure cafe'],
	'Buckle Consulting': ['buckle consu ltd'],
	'Freetrade': ['freetrade'],
	'Gourmet Burger Kitchen': ['gourmet burger kit'],
	'First Bus': ['first bus'],
	'Thatcher\'s Cider Tour': [],
	'Steam': ['steamgames.com'],
	'Sainsburys': ['sainsburys s/mkts'],
	'Southgate Carpark': ['southgate shopping'],
	'Mcdonalds': ['mcdonalds'],
	'Costa Coffee': ['costa coffee'],
	'Deliveroo': ['deliveroo.co.uk'],
	'Thujhan Yogeswaran': ['mr thujhan yogeswaran'],
	'Vishnuga Uthayamohan': ['vishnuga uthayamohan'],
	'Uber': ['uber *trip', 'uber trip', 'ubr* pending.uber.com'],
	'Oceana': ['southampton - oceana'],
	'Sainsburys Petrol': ['sainsburys petrol'],
	'Chick O Land': ['chick o land'],
	'Jesters': ['jester night'],
	'Dylan Marodeen': ['dylan marodeen', 'marodeen d j'],
	'Fatsoma': ['www.fatsoma.com'],
	'Southampton Catering': ['catering office'],
	'Handmade Burger Co': ['handmade burger co'],
	'The Crown Inn': [],
	'Asda': ['asda superstore'],
	'Millies Cookies': ['millies cookies'],
	'Nandos': ['nandos'],
	'Oscar Case': ['mr oscar david case'],
	'Josh Sanchez': ['sanchez carabal jf'],
	'Southampton SU': ['uni of southampton su'],
	'Uber Eats': ['uber eats help.uber.com'],
	'Bethany Shaw': ['miss bethany shaw'],
	'Franco Manca': ['franco manca'],
	'Sophie James': ['james sog'],
	'Google Play': ['google *google play'],
	'Disclosure and Barring Service': ['disclosure and barring'],
	'Pret A Manger': ['pret a manger'],
	'Sian Williams': ['williams c s'],
	'Tandem (internal)': ['tandem'],
}
