"""Move internal account target relationship

Revision ID: 4c430b37b01d
Revises: ea1ac3bfdff9
Create Date: 2020-03-25 23:58:55.645872

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from lucrum import database

revision = '4c430b37b01d'
down_revision = 'ea1ac3bfdff9'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('account', schema=None) as batch_op:
		batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=False, default=1))
		batch_op.create_foreign_key(batch_op.f('fk_account_target_id_target'), 'target', ['target_id'], ['id'])

	with op.batch_alter_table('target', schema=None) as batch_op:
		batch_op.drop_constraint('fk_target_internal_account_id_account', type_='foreignkey')
		batch_op.drop_column('internal_account_id')

	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('target', schema=None) as batch_op:
		batch_op.add_column(sa.Column('internal_account_id', sa.INTEGER(), nullable=True))
		batch_op.create_foreign_key('fk_target_internal_account_id_account', 'account', ['internal_account_id'], ['id'])

	with op.batch_alter_table('account', schema=None) as batch_op:
		batch_op.drop_constraint(batch_op.f('fk_account_target_id_target'), type_='foreignkey')
		batch_op.drop_column('target_id')

	# ### end Alembic commands ###
