"""Accounts refactor

Revision ID: ea1ac3bfdff9
Revises: a8cb774be1a5
Create Date: 2020-03-22 22:15:52.015255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1ac3bfdff9'
down_revision = 'a8cb774be1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_connection_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('connection_type', sa.Enum('PLAID', 'SCRAPE', 'API', name='connectiontype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.Enum('PLAID', 'SCRAPE', 'API', name='connectiontype'), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account_connection_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'max')
    op.drop_column('account', 'min')
    op.drop_column('account', 'bankLink_id')
    op.drop_column('account', 'balance')
    op.drop_column('account', 'identifier')
    op.drop_constraint(None, 'transaction_imported', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_imported', 'transaction', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'transaction_inferred', type_='foreignkey')
    op.drop_constraint(None, 'transaction_inferred', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_inferred', 'transaction', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction_inferred', 'target', ['target_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'transaction_manual', type_='foreignkey')
    op.drop_constraint(None, 'transaction_manual', type_='foreignkey')
    op.drop_constraint(None, 'transaction_manual', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_manual', 'method', ['method_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transaction_manual', 'target', ['target_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transaction_manual', 'transaction', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_manual', type_='foreignkey')
    op.drop_constraint(None, 'transaction_manual', type_='foreignkey')
    op.drop_constraint(None, 'transaction_manual', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_manual', 'target', ['target_id'], ['id'])
    op.create_foreign_key(None, 'transaction_manual', 'method', ['method_id'], ['id'])
    op.create_foreign_key(None, 'transaction_manual', 'transaction', ['id'], ['id'])
    op.drop_constraint(None, 'transaction_inferred', type_='foreignkey')
    op.drop_constraint(None, 'transaction_inferred', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_inferred', 'transaction', ['id'], ['id'])
    op.create_foreign_key(None, 'transaction_inferred', 'target', ['target_id'], ['id'])
    op.drop_constraint(None, 'transaction_imported', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_imported', 'transaction', ['id'], ['id'])
    op.add_column('account', sa.Column('identifier', sa.VARCHAR(length=80), nullable=True))
    op.add_column('account', sa.Column('balance', sa.FLOAT(), nullable=False))
    op.add_column('account', sa.Column('bankLink_id', sa.INTEGER(), nullable=True))
    op.add_column('account', sa.Column('min', sa.FLOAT(), nullable=True))
    op.add_column('account', sa.Column('max', sa.FLOAT(), nullable=True))
    op.create_foreign_key(None, 'account', 'bank_link', ['bankLink_id'], ['id'])
    op.drop_table('account_connection')
    op.drop_table('account_balance')
    op.drop_table('account_connection_user')
    # ### end Alembic commands ###
